name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Evita ejecuciones concurrentes innecesarias en el mismo ref
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: Backend (Flask) - Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sudoku-project/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: sudoku-project/backend/requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s tests -p "test_*.py"

  frontend-build:
    name: Frontend (Vite) - Build
    runs-on: ubuntu-latest
    needs: backend-tests

    defaults:
      run:
        working-directory: sudoku-project/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: sudoku-project/frontend/package-lock.json

      - name: Install
        run: npm ci

      # Si necesitas variables para build, define env aquí o usa GitHub Secrets
      # env:
      #   VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: sudoku-project/frontend/dist
          retention-days: 7
